In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab/placement_dataset.csv')
df.head()

   CGPA     IQ  Aptitude_Score  Communication_Skill  Internships Branch Placed
0  8.00   81.0            89.0                    1            1   MECH     No
1  7.36  105.0            74.0                    5            3  CIVIL    Yes
2  8.15   96.0            62.0                    6            1     IT     No
3  9.02  119.0            56.0                    6            2    CSE     No
4   NaN    NaN             NaN                    3            3    CSE    Yes

In [3]:
print(df.columns)

Index(['CGPA', 'IQ', 'Aptitude_Score', 'Communication_Skill', 'Internships',
       'Branch', 'Placed'],
      dtype='object')

In [4]:
print(df.columns)
df.head()

Index(['CGPA', 'IQ', 'Aptitude_Score', 'Communication_Skill', 'Internships',
       'Branch', 'Placed'],
      dtype='object')

   CGPA     IQ  Aptitude_Score  Communication_Skill  Internships Branch Placed
0  8.00   81.0            89.0                    1            1   MECH     No
1  7.36  105.0            74.0                    5            3  CIVIL    Yes
2  8.15   96.0            62.0                    6            1     IT     No
3  9.02  119.0            56.0                    6            2    CSE     No
4   NaN    NaN             NaN                    3            3    CSE    Yes

In [5]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CGPA                 190 non-null    float64
 1   IQ                   190 non-null    float64
 2   Aptitude_Score       190 non-null    float64
 3   Communication_Skill  200 non-null    int64
 4   Internships          200 non-null    int64
 5   Branch               200 non-null    object
 6   Placed               200 non-null    object
dtypes: float64(3), int64(2), object(2)
memory usage: 11.1+ KB

In [7]:
print(df.columns)

Index(['CGPA', 'IQ', 'Aptitude_Score', 'Communication_Skill', 'Internships',
       'Branch', 'Placed'],
      dtype='object')